---
title: "R 101"
subtitle: "A quick-and-dirty introduction to R" 
---

This tutorial covers basic R usage. 

You have probably been directed to this page because you are participating in a 
course that requires R programming. In that course, you will most likely use 
both R and RStudio. This tutorial comprises three exercises that are intended to 
guide you through the initial steps of getting up-and-running with R. 

Before you can do any R programming, however, you will need to install R and 
RStudio. The steps below will guide you through installing both R and RStudio. 
Please do so before proceeding on to the exercises. 


<!----------------------------------------------------------------------------->

# Course contents

### Installation

Before you start the exercises, make sure you can use R either locally on your 
PC or online through Posit Cloud.

- [Intsallation](exercises/installation.html)


### Exercises

This tutorial is broken into the following three exercises.

- [Exercise 1](exercises/exercise1.html)
- [Exercise 2](exercises/exercise2.html)
- [Exercise 3](exercises/exercise3.html)

### Solutions

Below, you can find suggested solutions for the above exercises. 

- [Exercise 1 Solutions](exercises/exercise1_solutions.html)
- [Exercise 2 Solutions](exercises/exercise2_solutions.html)
- [Exercise 3 Solutions](exercises/exercise3_solutions.html)

These solutions are provided so you can check your work and unstick yourself if
you really can't figure out one of the exercise questions. You should make a 
concerted effort to complete each exercise yourself before you view these 
solutions. You won't get much out of this tutorial if you skip right to the 
answers. 
